#!/usr/bin/python
# -*- coding: utf-8 -*-
definitions = {
    u"actuar": u"to act",
    u"afectar": u"to affect",
    u"afeitarse": u"to shave",
    u"ahorrar": u"to save",
    u"alimentarse": u"to eat",
    u"andar": u"to walk",
    u"arreglar": u"to fix",
    u"ayudar": u"to help",
    u"bailar": u"to dance",
    u"besar": u"to kiss",
    u"broncearse": u"to tan",
    u"bucear": u"to dive",
    u"buscar": u"to look for",
    u"cambiar": u"to change",
    u"caminar": u"to walk",
    u"cantar": u"to sing",
    u"cerrar": u"to close",
    u"cocinar": u"to cook",
    u"comprar": u"to buy",
    u"contestar": u"to answer",
    u"continuar": u"to continue",
    u"cortar": u"to cut",
    u"costar": u"to cost",
    u"cuidarse": u"to take care of yourself",
    u"dar": u"to give",
    u"darse": u"to give oneself",
    u"descansar": u"to rest",
    u"desear": u"to desire",
    u"dibujar": u"to draw",
    u"doblar": u"to turn",
    u"ducharse": u"to take a shower",
    u"eliminar": u"to eliminate",
    u"empezar": u"to begin",
    u"enseñar": u"to show/to teach",
    u"entrar": u"to enter",
    u"enviar": u"to send",
    u"escuchar": u"to listen",
    u"esperar": u"to hope/to wait",
    u"esquiar": u"to ski",
    u"estar": u"to be (emotions, etc.)",
    u"estudiar": u"to study",
    u"ganar": u"to earn/to win",
    u"gastar": u"to spend (money)",
    u"guardar": u"to keep",
    u"gustar": u"to please",
    u"hablar": u"to speak/to talk",
    u"jugar": u"to play (sports/games)",
    u"lavar": u"to wash",
    u"lavarse": u"to wash oneself",
    u"levantarse": u"to get up",
    u"limpiar": u"to clean",
    u"llamar": u"to call",
    u"llamarse": u"to be called",
    u"llegar": u"to arrive",
    u"llevar": u"to take/to carry/to wear",
    u"mandar": u"to send/to command",
    u"manejar": u"to drive",
    u"maquillarse": u"to put on makeup",
    u"mirar": u"to watch/to look",
    u"montar": u"to ride",
    u"nadar": u"to swim",
    u"necesitar": u"to need",
    u"olvidar": u"to forget",
    u"pagar": u"to pay",
    u"pasar": u"to pass/spend (time)",
    u"pasear": u"to take a walk",
    u"patinar": u"to skate",
    u"peinarse": u"to comb",
    u"pensar": u"to think/to plan",
    u"pesarse": u"to weigh oneself",
    u"pescar": u"to fish",
    u"planchar": u"to iron",
    u"planear": u"to plan",
    u"practicar": u"to practice",
    u"preguntar": u"to ask",
    u"preocuparse": u"to worry",
    u"preparar": u"to prepare",
    u"prepararse": u"to prepare oneself",
    u"presentar": u"to present",
    u"prestar": u"to lend",
    u"quedar": u"to stay/to remain",
    u"quedarse": u"to stay/to remain",
    u"quitar": u"to remove/to take off",
    u"quitarse": u"to remove/take off",
    u"recordar": u"to remember",
    u"regresar": u"to return",
    u"sacar": u"to take out/to get",
    u"saltar": u"to jump",
    u"secarse": u"to dry oneself",
    u"terminar": u"to finish",
    u"tocar": u"to touch/to play (instruments)",
    u"tomar": u"to take",
    u"trabajar": u"to work",
    u"usar": u"to use",
    u"viajar": u"to travel",
    u"visitar": u"to visit",
    u"vomitar": u"to vomit",
    u"aprender": u"to learn",
    u"barrer": u"to sweep",
    u"beber": u"to drink",
    u"caer": u"to fall",
    u"comer": u"to eat",
    u"comprender": u"to understand/to comprehend",
    u"conocer": u"to know (personal), to meet",
    u"correr": u"to run/to jog",
    u"creer": u"to believe",
    u"deber": u"to ought to (should)",
    u"doler": u"to hurt",
    u"entender": u"to understand",
    u"haber": u"to have (done)",
    u"hacer": u"to do/to make",
    u"leer": u"to read",
    u"llover": u"to rain",
    u"mantenerse": u"to maintain oneself",
    u"ofrecer": u"to offer",
    u"parecer": u"to appear (to be)",
    u"perder": u"to lose",
    u"poder": u"to be able to",
    u"poner": u"to put",
    u"ponerse": u"to put on",
    u"prometer": u"to promise",
    u"querer": u"to want",
    u"responder": u"to respond",
    u"romper": u"to break",
    u"saber": u"to know (information)",
    u"satisfacer": u"to satisfy",
    u"ser": u"to be (description)",
    u"tener": u"to have (a possession)",
    u"traer": u"to bring",
    u"valer": u"to be worth",
    u"vender": u"to sell",
    u"ver": u"to see",
    u"abrir": u"to open",
    u"asistir": u"to attend",
    u"cubrir": u"to cover",
    u"cumplir": u"to complete",
    u"decidir": u"to decide",
    u"decir": u"to say/to tell",
    u"divertirse": u"to have fun",
    u"dividir": u"to divide",
    u"dormir": u"to sleep",
    u"dormirse": u"to fall asleep",
    u"escribir": u"to write",
    u"ir": u"to go",
    u"irse": u"to leave",
    u"oír": u"to hear",
    u"pedir": u"to ask for/to order (food)",
    u"permitir": u"to permit/to allow",
    u"preferir": u"to prefer",
    u"recibir": u"to receive",
    u"reírse": u"to laugh",
    u"salir": u"to leave/to go out",
    u"sobrevivir": u"to survive",
    u"sonreírse": u"to smile",
    u"subirse": u"to go up",
    u"sufrir": u"to suffer",
    u"traducir": u"to translate",
    u"venir": u"to come",
    u"sentirse": u"to feel",
    u"vestirse": u"to get dressed",
    u"vivir": u"to live"
}
